'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('Venues', [
        {
        name: 'Mucky Duck',
        image: 'https://static.wixstatic.com/media/18a41e_b2ed55d5bd2a47c68c1bdd0a674e95dd~mv2.jpg/v1/fill/w_497,h_396,al_c,q_80,usm_0.66_1.00_0.01/18a41e_b2ed55d5bd2a47c68c1bdd0a674e95dd~mv2.webp',
        website: 'https://www.muckyduckpub.com/',
        location: '1315 9th Ave, San Francisco, CA 94122',
        description: `The World Famous Mucky Duck is the inner Sunsets favorite friendly pub.  With over 10 TVs we always have a game on.  Play some pool or shoot darts while you and the friends watch the games.  With some of the best bartenders around and plenty of locals a good time is always to be had.  Think of us as your local bar- even if you're not from here!`,
        nfl: true,
        mlb: true,
        nba: true,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },
        {
        name: 'Kezar Pub',
        image: 'https://cdn.vox-cdn.com/thumbor/oUugxlzrZgRWDUtMzwm9vRZHhsc=/0x0:700x525/1200x900/filters:focal(294x207:406x319):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/62591307/Kezar.0.0.0.jpg',
        website: 'https://www.yelp.com/biz/the-kezar-pub-san-francisco-2',
        location: '770 Stanyan St, San Francisco, CA 94117',
        description: `Fans cheer all kinds of sports on flat-screens throughout this spot serving pub grub & beer on tap.`,
        nfl: true,
        mlb: false,
        nba: true,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },
        {
        name: "Yancy's Saloon",
        image: 'https://10619-2.s.cdn12.com/rests/original/802_3218340.jpg',
        website: 'https://www.yelp.com/biz/yancys-saloon-san-francisco',
        location: '734 Irving St, San Francisco, CA 94122',
        description: `Low-key watering hole with kitschy decor & TVs playing all manner of games, plus lots of dartboards.`,
        nfl: true,
        mlb: true,
        nba: true,
        nhl: true,
        ncaa: false,
        createdAt: new Date(),
        updatedAt: new Date()
        },
        {
        name: 'Blackthorn Sports Bar',
        image: 'https://pbs.twimg.com/media/ETRL3KfU8AAj7LN.jpg',
        website: 'http://blackthornsf.com/',
        location: '834 Irving St, San Francisco, CA 94122',
        description: `Laid-back Irish bar with ample flat-screens & weekly events like karaoke, trivia & DJ nights.`,
        nfl: true,
        mlb: true,
        nba: false,
        nhl: true,
        ncaa: false,
        createdAt: new Date(),
        updatedAt: new Date()
        },
        {
        name: 'Little Shamrock',
        image: 'https://img.hoodline.com/uploads/story/image/11083/exterior.jpg',
        website: 'https://en.wikipedia.org/wiki/The_Little_Shamrock',
        location: '807 Lincoln Way, San Francisco, CA 94122',
        description: `Idiosyncratic Irish pub drawing in locals with pints, board games & free popcorn.`,
        nfl: false,
        mlb: true,
        nba: true,
        nhl: false,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: "Murio's Trophy Room",
        image: 'https://s3-media0.fl.yelpcdn.com/bphoto/nGK1hfxguJZx2Pkf7xPTKg/l.jpg',
        website: 'https://www.yelp.com/biz/murios-trophy-room-san-francisco',
        location: '1811 Haight St, San Francisco, CA 94117',
        description: `Roomy, old-school watering hole with draft beer & a funky vibe, plus a jukebox & billiards table.`,
        nfl: true,
        mlb: false,
        nba: false,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: 'Finnegans Wake',
        image: 'https://s3-media0.fl.yelpcdn.com/bphoto/PrsmikO-UwLOY6Q03U16xw/o.jpg',
        website: 'https://www.finneganssf.com/',
        location: '937 Cole St, San Francisco, CA 94117',
        description: `Basic pub known for Bloody Marys & a patio space, plus Ping-Pong, pool, video games & TVs.`,
        nfl: false,
        mlb: false,
        nba: true,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },
        {
        name: "Nickie's",
        image: 'http://img1.wsimg.com/isteam/ip/2f3232ff-7c37-4cd0-a04a-32f5c25b6a7e/outdoors%20-%20Edited%20(1).jpg',
        website: 'https://nickiesbarsf.com/',
        location: '466 Haight St, San Francisco, CA 94117',
        description: `From trivia nights to football screenings, this pub-grub & dance spot hosts a variety of events.`,
        nfl: false,
        mlb: true,
        nba: false,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: 'Fireside Bar',
        image: 'https://www.sfexaminer.com/wp-content/uploads/2020/01/20184663_web1_20200116_162045.jpg',
        website: 'https://www.yelp.com/biz/fireside-bar-san-francisco',
        location: '603 Irving St, San Francisco, CA 94122',
        description: `Relaxed bar pleasing locals & UCSF students with its cozy fireplace, overstuffed sofas & jukebox.`,
        nfl: true,
        mlb: true,
        nba: true,
        nhl: false,
        ncaa: false,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: "Hobson's Choice",
        image: 'https://tableagent.s3.amazonaws.com/media/originals/2962_6703.jpg',
        website: 'http://www.hobsonschoice.com/',
        location: '1601 Haight St, San Francisco, CA 94117',
        description: `Rum specialist pouring fruity punches in an old Victorian house setting with loungey sofa seating.`,
        nfl: true,
        mlb: true,
        nba: false,
        nhl: false,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: 'Underdogs Tres',
        image: 'https://fastly.4sqi.net/img/general/600x600/36104729_jd63Sjbvk-fkvQzDwB3ba1S_g8KMh719COFp2HDNq2U.jpg',
        website: 'https://underdogstres.com/',
        location: '1224 9th Ave, San Francisco, CA 94122',
        description: `Compact hangout provides familiar Mexican street eats & cocktails in a sports-themed space with TVs.`,
        nfl: false,
        mlb: true,
        nba: false,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        }, 
        {
        name: 'Chug Pub',
        image: 'https://www.sfexaminer.com/wp-content/uploads/2020/10/23103456_web1_201025-SFE-Saul-Chug_1.jpg',
        website: 'http://chugpub.com/',
        location: '1849 Lincoln Way, San Francisco, CA 94122',
        description: `Neighborhood bar with weekly beer specials known for its Chug Tower, a 3-liter serving of suds.`,
        nfl: false,
        mlb: true,
        nba: false,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },
        {
        name: 'Hi Tops',
        image: 'https://static.wixstatic.com/media/923f2b_052a6eb0b137468d88330708a9312420~mv2_d_2048_1365_s_2.jpg/v1/fill/w_640,h_482,al_c,q_80,usm_0.66_1.00_0.01/923f2b_052a6eb0b137468d88330708a9312420~mv2_d_2048_1365_s_2.webp',
        website: 'https://www.hitopsbar.com/',
        location: '2247 Market St, San Francisco, CA 94114',
        description: `Gay bar supplying top-shelf fast food & drinks plus TVs tuned to sports in a setting with gym decor.`,
        nfl: true,
        mlb: true,
        nba: true,
        nhl: true,
        ncaa: false,
        createdAt: new Date(),
        updatedAt: new Date()
        },
        {
        name: 'Phat Philly',
        image: 'https://i.ytimg.com/vi/cIs6qNR0mwg/maxresdefault.jpg',
        website: 'http://www.phat-philly.com/',
        location: '3388 24th St, San Francisco, CA 94110',
        description: `Various kinds of cheesesteaks & more, plus housemade sauces like barbecue & cheddar-beer.`,
        nfl: true,
        mlb: true,
        nba: true,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: 'Golden Gate Tap Room',
        image: 'https://www.sftravel.com/sites/sftravel.prod.acquia-sites.com/files/field/image/Golden-Gate-Tap-Room.jpg',
        website: 'https://www.ggtaproom.com/',
        location: '449 Powell St, San Francisco, CA 94108',
        description: `Sprawling spot with retro furnishings featuring 100+ beers, numerous TVs plus video & table games.`,
        nfl: true,
        mlb: true,
        nba: true,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: "Murphy's Pub",
        image: 'https://media-cdn.tripadvisor.com/media/photo-s/04/b0/9a/bd/the-bar.jpg',
        website: 'https://www.yelp.com/biz/murphys-pub-san-francisco',
        location: '217 Kearny St, San Francisco, CA 94108',
        description: `Brick-walled pub with dim lighting featuring bar food, sports TV & a free comedy night.`,
        nfl: true,
        mlb: true,
        nba: false,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: 'Giordano Brothers',
        image: 'https://tableagent.s3.amazonaws.com/media/originals/2905_7532.jpg',
        website: 'https://www.giordanobros.com/',
        location: ' 3108 16th St, San Francisco, CA 94103',
        description: `Beer, sports TV, shuffleboard & Pittsburgh-style sandwiches (with fries & coleslaw in the middle).`,
        nfl: true,
        mlb: true,
        nba: true,
        nhl: true,
        ncaa: false,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: 'Hockey Haven',
        image: 'https://9968c6ef49dc043599a5-e151928c3d69a5a4a2d07a8bf3efa90a.ssl.cf2.rackcdn.com/47320-1.jpg',
        website: 'https://hockey-haven.business.site/',
        location: '3625 Balboa St #2603, San Francisco, CA',
        description: `Casual neighborhood bar equipped with flat-screen TVs, a pool table & a jukebox.`,
        nfl: true,
        mlb: false,
        nba: false,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: 'Hearth Bar',
        image: 'https://cdn.vox-cdn.com/thumbor/WQQhITzziNXvRM3c15pepcQI60Q=/0x0:720x480/1200x900/filters:focal(303x183:417x297):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/62518973/545039_10150894846251679_915219313_n.0.0.jpg',
        website: 'https://www.yelp.com/biz/the-hearth-san-francisco',
        location: '4701 Geary Blvd, San Francisco, CA 94118',
        description: `Cozy, laid-back neighborhood watering hole offering a pool table, darts & other arcade games.`,
        nfl: true,
        mlb: true,
        nba: true,
        nhl: true,
        ncaa: true,
        createdAt: new Date(),
        updatedAt: new Date()
        },        
        {
        name: 'The Page',
        image: 'https://s.hdnux.com/photos/01/14/47/17/20083708/9/rawImage.jpg',
        website: 'http://www.thepagebar.com/',
        location: '298 Divisadero St, San Francisco, CA 94117',
        description: `No-frills spot featuring exposed-brick walls, animal-head decor & a variety of beers. Cash only.`,
        nfl: true,
        mlb: true,
        nba: false,
        nhl: true,
        ncaa: false,
        createdAt: new Date(),
        updatedAt: new Date()
        },
      ], {});
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
  }
};
